language: node_js
node_js:
  - "8"

script:
  - npm run lint
  - npm run test:unit
  - npm run docker:start
  - npm run test:e2e
  - npm run docker:stop
  - npm run test:cover

after_script:
  - npm run test:cover:check
